### ISSUE TITLE
ReflectionException - Class view does not exist

### ISSUE THREAD

**Issue by Daem0nX** [binarix/Laravel-Foundation-Pagination#2]
Laravel 4.0.7 - Using the default Pagination works as expected. Modified composer.json and ran composer update, after updating app/config/app.php and app/config/view.php I receive the following.

ReflectionException
Class view does not exist
open: /domain.com/vendor/laravel/framework/src/Illuminate/Container/Container.php
    // hand back the results of the functions, which allows functions to be
    // used as resolvers for more fine-tuned resolution of these objects.
    if ($concrete instanceof Closure)
    {
    return $concrete($this, $parameters);
    }
    $reflector = new \ReflectionClass($concrete);
    // If the type is not instantiable, the developer is attempting to resolve

**Comment by binarix** [comment]
Not sure what is causing this error. Anyone else having this issue?

**Comment by Daem0nX** [comment]
After having it work in another project I went back to investigate this issue. Without realizing it I had added Binarix\Foundation right after Illuminate\Pagination instead of appending it to the list as a new provider. Once the position was fixed it worked. Thank you for making this package.

**Comment by cawecoy** [comment]
Hi @Daem0nX .

I am not using Laravel-Foundation-Pagination, but I am having a similar issue after upgrading to Laravel 4.1, and I can't find almost any information about this issue.

When I run any artisan command on terminal, I get this error: 

```
{"error":{"type":"ReflectionException","message":"Class view does not exist","file":"\/domain.com\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":501}}
```

which is in the same line than your.

My providers:

```
    'providers' => array(

        'Illuminate\Foundation\Providers\ArtisanServiceProvider',
        'Illuminate\Auth\AuthServiceProvider',
        'Illuminate\Cache\CacheServiceProvider',
        'Illuminate\Foundation\Providers\CommandCreatorServiceProvider',
        'Illuminate\Session\CommandsServiceProvider',
        'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
        'Illuminate\Foundation\Providers\ComposerServiceProvider',
        'Illuminate\Routing\ControllerServiceProvider',
        'Illuminate\Cookie\CookieServiceProvider',
        'Illuminate\Database\DatabaseServiceProvider',
        'Illuminate\Encryption\EncryptionServiceProvider',
        'Illuminate\Filesystem\FilesystemServiceProvider',
        'Illuminate\Hashing\HashServiceProvider',
        'Illuminate\Html\HtmlServiceProvider',
        'Illuminate\Foundation\Providers\KeyGeneratorServiceProvider',
        'Illuminate\Log\LogServiceProvider',
        'Illuminate\Mail\MailServiceProvider',
        'Podesta\Mail\MailServiceProvider',
        'Illuminate\Foundation\Providers\MaintenanceServiceProvider',
        'Illuminate\Database\MigrationServiceProvider',
        'Illuminate\Foundation\Providers\OptimizeServiceProvider',
        'Illuminate\Pagination\PaginationServiceProvider',
        'Illuminate\Foundation\Providers\PublisherServiceProvider',
        'Illuminate\Queue\QueueServiceProvider',
        'Illuminate\Redis\RedisServiceProvider',
        'Illuminate\Remote\RemoteServiceProvider',
        'Illuminate\Auth\Reminders\ReminderServiceProvider',
        'Illuminate\Foundation\Providers\RouteListServiceProvider',
        'Illuminate\Database\SeedServiceProvider',
        'Illuminate\Foundation\Providers\ServerServiceProvider',
        'Illuminate\Session\SessionServiceProvider',
        'Illuminate\Foundation\Providers\TinkerServiceProvider',
        'Illuminate\Translation\TranslationServiceProvider',
        'Illuminate\Validation\ValidationServiceProvider',
        'Illuminate\View\ViewServiceProvider',
        'Illuminate\Workbench\WorkbenchServiceProvider',
        'Toddish\Verify\VerifyServiceProvider',
        'Former\FormerServiceProvider',
        'Basset\BassetServiceProvider',
        'Cviebrock\EloquentSluggable\SluggableServiceProvider',
        'Bootstrapper\BootstrapperServiceProvider',
        'KennedyTedesco\Validation\ValidationServiceProvider',
        'Intervention\Image\ImageServiceProvider',
        'Aws\Laravel\AwsServiceProvider',
        'Barryvdh\Debugbar\ServiceProvider',
        'Maatwebsite\Excel\ExcelServiceProvider',
    ),
```

I just did `composer update` and `composer dump-autoload`. Nothing on logs. I don't know what to do!

Can you help me? Any idea?

**Comment by cawecoy** [comment]
I found the solution, it's also in the service providers: `'Podesta\Mail\MailServiceProvider',` can't be listed before any `Illuminate` service, I put it after `'Illuminate\Workbench\WorkbenchServiceProvider',` and now it's OK.
