### ISSUE TITLE
No stable release

### ISSUE THREAD

**Issue by thomaswelton** [binarix/Laravel-Foundation-Pagination#5]
Please tag a release and update the readme to discourage the use of installing dev-master

**Comment by binarix** [comment]
Tagged 1.0.0 for laravel 4.0.x/4.1.x and updated readme

**Comment by thomaswelton** [comment]
Thanks

**Comment by thomaswelton** [comment]
@binarix sorry dude, would be good too if you add license information to the composer.json

**Comment by binarix** [comment]
added. sorry that took a while.
